sections:
  - name: Demo
    id: 360004898138
    articles:
      - id: 360016703297
        title: SSL Certificates and Collector
        file: ../demo/ssl-certificates-and-collector.md
        hash: Ns9cEfv2h6z3Xu6tte04WQYF+VQhtZcvAp9wIGVHVz4=
        webLink: 'https://support.snowplowanalytics.com/hc/en-us/articles/360016703297'
      - id: 360016719917
        title: Bump Elasticsearch
        file: ../demo/bump-elasticsearch.md
        hash: mByfqnhB+aGRibm0avitEg2mTqCNSKcbDv46oPLVudU=
        webLink: 'https://support.snowplowanalytics.com/hc/en-us/articles/360016719917'
      - id: 360016730697
        title: This is a Demo Image
        file: ../demo/This-is-a-Demo-Image.md
        hash: CRJPZ6Dr+PyGA2JSS/yKNX28fZdL1ps0iuarr0UKq4M=
        webLink: 'https://support.snowplowanalytics.com/hc/en-us/articles/360016730697'
