sections:
  - name: Demo
    id: 360004898138
    articles:
      - id: 360016703297
        title: SSL Certificates and Collector
        file: ../demo/ssl-certificates-and-collector.md
        hash: Ns9cEfv2h6z3Xu6tte04WQYF+VQhtZcvAp9wIGVHVz4=
        webLink: 'https://support.snowplowanalytics.com/hc/en-us/articles/360016703297'
      - id: 360016719917
        title: Bump Elasticsearch
        file: ../demo/bump-elasticsearch.md
        hash: mByfqnhB+aGRibm0avitEg2mTqCNSKcbDv46oPLVudU=
        webLink: 'https://support.snowplowanalytics.com/hc/en-us/articles/360016719917'
      - id: 360016743757
        title: Sending an Image
        file: ../demo/Sending-an-Image.md
        hash: LrSuawWPdAMTF5riGV50v47iblXptWP5Ah0VcbEPU70=
        webLink: 'https://support.snowplowanalytics.com/hc/en-us/articles/360016743757'
  - name: 54 ElasticSearch
    id: 360004924518
    articles:
      - id: 360016825358
        title: 54.01 ES nodes and shards correlation
        file: ../demo/54.01-ES-nodes-and-shards-correlation.md
        hash: 0/uDZsiQS5a3S47MjnBq6RBLOnJpK2c46gGMUU407po=
        webLink: 'https://support.snowplowanalytics.com/hc/en-us/articles/360016825358'
  - name: 21 Collector
    id: 360004961638
    articles:
      - id: 360016902217
        title: 21.01 Cookies Set by Snowplow Collector
        file: ../demo/21.01-Cookies-Set-by-Snowplow-Collector.md
        hash: 32XaX/LlgWhKQTm0+NjPSeg54mJY7sm8wfsFtHghKm8=
        webLink: 'https://support.snowplowanalytics.com/hc/en-us/articles/360016902217'
